# Generated by Django 5.0.3 on 2024-09-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField(null=True)),
                ("address", models.CharField(max_length=250, null=True)),
                ("work", models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
